# nginx proxy address - http://172.17.0.1:62000

name: librespeed
x-logging: &default-logging
  options:
    max-size: '5m'
    max-file: '1'
  driver: json-file

services:
  app:
    image: ghcr.io/librespeed/speedtest:latest
    container_name: librespeed-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    pull_policy: always
    logging: *default-logging
    environment:
      TZ: ${TZ:-America/New_York}
      CONTAINER_NAME: librespeed-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
      WEBPORT: 80
      DISTANCE: mi
      MODE: standalone
      DB_TYPE: sqlite
      TELEMETRY: true
      DISABLE_IPINFO: false
      REDACT_IP_ADDRESSES: false
      ENABLE_ID_OBFUSCATION: true
      TITLE: ${APP_ORG_NAME:-LibreSpeed} SpeedTest
      EMAIL: ${EMAIL_SERVER_MAIL_FROM:-no-reply@example.com}
      PASSWORD: ${APP_ADMIN_PASS:-changeme_admin_password}
      IPINFO_APIKEY: ${IPINFO_APIKEY:-}
    ports:
      - '172.17.0.1:62000:80'
    volumes:
      - './volumes/data/librespeed:/database:z'
      - './volumes/config/librespeed:/config:z'
    networks:
      - librespeed
      - proxy
      - cloudflare
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://librespeed-app:80'
      - 'cloudflare.hostname=librespeed.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.librespeed-app.entrypoints=http'
      - 'traefik.http.routers.librespeed-app-secure.tls=true'
      - 'traefik.http.routers.librespeed-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.librespeed-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.librespeed-app.middlewares=librespeed-app-https-redirect'
      - 'traefik.http.routers.librespeed-app-secure.entrypoints=https'
      - 'traefik.http.routers.librespeed-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.librespeed-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.librespeed-app-secure.service=librespeed-app'
      - 'traefik.http.services.librespeed-app.loadbalancer.server.port=80'

networks:
  librespeed:
    name: librespeed
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
